[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Production 환경 설정
[context.production]
  command = "npm run build"

# SPA를 위한 catch-all 리다이렉트 (역할 제한 없음)
# 이 리다이렉트는 모든 사용자가 접근할 수 있어야 하므로 조건부 제한을 제거
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 라우트나 특정 경로에 대한 역할 기반 접근 제어 (필요한 경우)
# [[redirects]]
#   from = "/admin/*"
#   to = "/admin-login.html"
#   status = 302
#   conditions = {Role = ["admin"]}

# [[redirects]]
#   from = "/editor/*"  
#   to = "/editor-login.html"
#   status = 302
#   conditions = {Role = ["admin", "editor"]}

[headers]
  # 보안 헤더 설정
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"